// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vinyltap.proto

package vinyltap

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Album struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Artist               string   `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ReleaseDate          int64    `protobuf:"varint,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Songs                []string `protobuf:"bytes,5,rep,name=songs,proto3" json:"songs,omitempty"`
	Tombstoned           bool     `protobuf:"varint,6,opt,name=tombstoned,proto3" json:"tombstoned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Album) Reset()         { *m = Album{} }
func (m *Album) String() string { return proto.CompactTextString(m) }
func (*Album) ProtoMessage()    {}
func (*Album) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0181488c785c5a2, []int{0}
}

func (m *Album) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Album.Unmarshal(m, b)
}
func (m *Album) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Album.Marshal(b, m, deterministic)
}
func (m *Album) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Album.Merge(m, src)
}
func (m *Album) XXX_Size() int {
	return xxx_messageInfo_Album.Size(m)
}
func (m *Album) XXX_DiscardUnknown() {
	xxx_messageInfo_Album.DiscardUnknown(m)
}

var xxx_messageInfo_Album proto.InternalMessageInfo

func (m *Album) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Album) GetArtist() string {
	if m != nil {
		return m.Artist
	}
	return ""
}

func (m *Album) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Album) GetReleaseDate() int64 {
	if m != nil {
		return m.ReleaseDate
	}
	return 0
}

func (m *Album) GetSongs() []string {
	if m != nil {
		return m.Songs
	}
	return nil
}

func (m *Album) GetTombstoned() bool {
	if m != nil {
		return m.Tombstoned
	}
	return false
}

func init() {
	proto.RegisterType((*Album)(nil), "vinyltap.Album")
}

func init() { proto.RegisterFile("vinyltap.proto", fileDescriptor_b0181488c785c5a2) }

var fileDescriptor_b0181488c785c5a2 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x40, 0x49, 0x63, 0x4a, 0x1d, 0x65, 0x85, 0x41, 0x24, 0x78, 0x90, 0xe8, 0xc5, 0x9c, 0x8a,
	0xe8, 0x17, 0x08, 0x82, 0xf7, 0xe8, 0x59, 0x49, 0xc9, 0x20, 0x81, 0x6c, 0x53, 0x9a, 0x51, 0xf0,
	0x67, 0xfc, 0x56, 0xd9, 0xb4, 0x8a, 0x78, 0xd9, 0xe3, 0x7b, 0xcc, 0x83, 0x99, 0x81, 0xcd, 0x47,
	0x1c, 0x3f, 0x13, 0xfb, 0xa9, 0x9f, 0xe6, 0xcc, 0x19, 0xbb, 0x1f, 0xbe, 0xfa, 0x12, 0xa0, 0xee,
	0xd3, 0xf0, 0xbe, 0xc5, 0x0d, 0x34, 0x31, 0x68, 0x61, 0x84, 0x55, 0xae, 0x89, 0x01, 0xcf, 0xa0,
	0xf5, 0x33, 0xc7, 0xc2, 0xba, 0x31, 0xc2, 0x1e, 0xba, 0x95, 0xf0, 0x14, 0x14, 0x47, 0x4e, 0xa4,
	0x65, 0xd5, 0x0b, 0xe0, 0x25, 0x1c, 0xcf, 0x94, 0xc8, 0x17, 0x7a, 0x0d, 0x9e, 0x49, 0x1f, 0x18,
	0x61, 0xa5, 0x3b, 0x5a, 0xdd, 0x83, 0x67, 0xda, 0x85, 0x25, 0x8f, 0x6f, 0x45, 0x2b, 0x23, 0x77,
	0x61, 0x05, 0xbc, 0x00, 0xe0, 0xbc, 0x1d, 0x0a, 0xe7, 0x91, 0x82, 0x6e, 0x8d, 0xb0, 0x9d, 0xfb,
	0x63, 0x6e, 0x5f, 0x40, 0x3e, 0xfb, 0x09, 0x7b, 0xe8, 0x1e, 0x89, 0x97, 0x4d, 0x4f, 0xfa, 0xdf,
	0x73, 0xaa, 0x38, 0xff, 0x2f, 0x6e, 0x04, 0x5e, 0x83, 0x7c, 0x22, 0xde, 0x3f, 0x3a, 0xb4, 0xf5,
	0x23, 0x77, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x53, 0x44, 0xae, 0x23, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TapClient is the client API for Tap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TapClient interface {
	GetAlbum(ctx context.Context, in *Album, opts ...grpc.CallOption) (Tap_GetAlbumClient, error)
	Set(ctx context.Context, in *Album, opts ...grpc.CallOption) (*Album, error)
}

type tapClient struct {
	cc *grpc.ClientConn
}

func NewTapClient(cc *grpc.ClientConn) TapClient {
	return &tapClient{cc}
}

func (c *tapClient) GetAlbum(ctx context.Context, in *Album, opts ...grpc.CallOption) (Tap_GetAlbumClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tap_serviceDesc.Streams[0], "/vinyltap.Tap/GetAlbum", opts...)
	if err != nil {
		return nil, err
	}
	x := &tapGetAlbumClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tap_GetAlbumClient interface {
	Recv() (*Album, error)
	grpc.ClientStream
}

type tapGetAlbumClient struct {
	grpc.ClientStream
}

func (x *tapGetAlbumClient) Recv() (*Album, error) {
	m := new(Album)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tapClient) Set(ctx context.Context, in *Album, opts ...grpc.CallOption) (*Album, error) {
	out := new(Album)
	err := c.cc.Invoke(ctx, "/vinyltap.Tap/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TapServer is the server API for Tap service.
type TapServer interface {
	GetAlbum(*Album, Tap_GetAlbumServer) error
	Set(context.Context, *Album) (*Album, error)
}

// UnimplementedTapServer can be embedded to have forward compatible implementations.
type UnimplementedTapServer struct {
}

func (*UnimplementedTapServer) GetAlbum(req *Album, srv Tap_GetAlbumServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAlbum not implemented")
}
func (*UnimplementedTapServer) Set(ctx context.Context, req *Album) (*Album, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}

func RegisterTapServer(s *grpc.Server, srv TapServer) {
	s.RegisterService(&_Tap_serviceDesc, srv)
}

func _Tap_GetAlbum_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Album)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TapServer).GetAlbum(m, &tapGetAlbumServer{stream})
}

type Tap_GetAlbumServer interface {
	Send(*Album) error
	grpc.ServerStream
}

type tapGetAlbumServer struct {
	grpc.ServerStream
}

func (x *tapGetAlbumServer) Send(m *Album) error {
	return x.ServerStream.SendMsg(m)
}

func _Tap_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Album)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vinyltap.Tap/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapServer).Set(ctx, req.(*Album))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vinyltap.Tap",
	HandlerType: (*TapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _Tap_Set_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAlbum",
			Handler:       _Tap_GetAlbum_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vinyltap.proto",
}
