// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vinyltap.proto

package vinyltap

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Album struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Artist               string   `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ReleaseDate          int64    `protobuf:"varint,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Songs                []string `protobuf:"bytes,5,rep,name=songs,proto3" json:"songs,omitempty"`
	Tombstoned           bool     `protobuf:"varint,6,opt,name=tombstoned,proto3" json:"tombstoned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Album) Reset()         { *m = Album{} }
func (m *Album) String() string { return proto.CompactTextString(m) }
func (*Album) ProtoMessage()    {}
func (*Album) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0181488c785c5a2, []int{0}
}

func (m *Album) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Album.Unmarshal(m, b)
}
func (m *Album) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Album.Marshal(b, m, deterministic)
}
func (m *Album) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Album.Merge(m, src)
}
func (m *Album) XXX_Size() int {
	return xxx_messageInfo_Album.Size(m)
}
func (m *Album) XXX_DiscardUnknown() {
	xxx_messageInfo_Album.DiscardUnknown(m)
}

var xxx_messageInfo_Album proto.InternalMessageInfo

func (m *Album) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Album) GetArtist() string {
	if m != nil {
		return m.Artist
	}
	return ""
}

func (m *Album) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Album) GetReleaseDate() int64 {
	if m != nil {
		return m.ReleaseDate
	}
	return 0
}

func (m *Album) GetSongs() []string {
	if m != nil {
		return m.Songs
	}
	return nil
}

func (m *Album) GetTombstoned() bool {
	if m != nil {
		return m.Tombstoned
	}
	return false
}

func init() {
	proto.RegisterType((*Album)(nil), "vinyltap.Album")
}

func init() { proto.RegisterFile("vinyltap.proto", fileDescriptor_b0181488c785c5a2) }

var fileDescriptor_b0181488c785c5a2 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0x41, 0xaa, 0xc2, 0x30,
	0x10, 0xc6, 0x71, 0xd2, 0xbe, 0x94, 0xbe, 0x51, 0xba, 0x08, 0x22, 0xb3, 0x92, 0xe8, 0x2a, 0x2b,
	0x37, 0x9e, 0x40, 0xf0, 0x04, 0xb9, 0x80, 0xa4, 0x64, 0x90, 0x40, 0xda, 0x94, 0x66, 0x14, 0xbc,
	0x8c, 0x67, 0x95, 0xd6, 0x0a, 0x2e, 0x7f, 0x7f, 0xf8, 0xe0, 0x83, 0xe6, 0x11, 0xfa, 0x67, 0x64,
	0x37, 0x1c, 0x87, 0x31, 0x71, 0x52, 0xf5, 0xd7, 0x87, 0x97, 0x00, 0x79, 0x8e, 0xed, 0xbd, 0x53,
	0x0d, 0x14, 0xc1, 0xa3, 0xd0, 0xc2, 0x48, 0x5b, 0x04, 0xaf, 0xb6, 0x50, 0xb9, 0x91, 0x43, 0x66,
	0x2c, 0xb4, 0x30, 0xff, 0x76, 0x91, 0xda, 0x80, 0xe4, 0xc0, 0x91, 0xb0, 0x9c, 0xf3, 0x07, 0x6a,
	0x0f, 0xeb, 0x91, 0x22, 0xb9, 0x4c, 0x57, 0xef, 0x98, 0xf0, 0x4f, 0x0b, 0x53, 0xda, 0xd5, 0xd2,
	0x2e, 0x8e, 0x69, 0x1a, 0xe6, 0xd4, 0xdf, 0x32, 0x4a, 0x5d, 0x4e, 0xc3, 0x19, 0x6a, 0x07, 0xc0,
	0xa9, 0x6b, 0x33, 0xa7, 0x9e, 0x3c, 0x56, 0x5a, 0x98, 0xda, 0xfe, 0x94, 0xb6, 0x9a, 0x1f, 0x9f,
	0xde, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x9b, 0x27, 0x7f, 0xc3, 0x00, 0x00, 0x00,
}
